baseURL = "http://food.hannah-and-jakob.ca/"
languageCode = "en-us"
title = "Food I Made (or ate)"
theme = "food-theme"
defaultContentLanguage = "en"
copyright = "&copy; 2020"
enableGitInfo = true

[author]

name = "Jakob Külzer"

[build]

publishResources = false

[menu]

[[menu.main]]

identifier = "tags"
name = "Tags"
url = "/tags/"

[[menu.theresmore]]

identifier = "tags"
name = "tags"
url = "/tags/"
title = "Tags"



[permalinks]
posts = "/:year/:month/:slug/"

[params]
Subtitle = "One delicious meal at a time"

[imaging]

resampleFilter = "lanczos"
quality = 85
disableLatLong = true

