# This is a basic workflow to help you get started with Actions

name: build static site

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: install hugo
      run: mkdir bin && cd bin && curl -L https://github.com/gohugoio/hugo/releases/download/v0.69.1/hugo_0.69.1_Linux-64bit.tar.gz | tar xzv

    - name: enable lfs
      run: git lfs install
      
    - name: list stuff
      run: find ./
      
    - name: hugo build
      run: PATH=./bin:$PATH make build
      
      
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: ls -l $GITHUB_WORKSPACE

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
